language: php
php:
  - '5.6'
  - '7.0'
  - nightly
script: phpunit --bootstrap phuria/sql-builder/vendor/autoload.php --configuration phuria/sql-builder/phpunit.xml phuria/sql-builder/tests --teamcity