language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'
  - 'hhvm'
install:
  - 'composer install'
  - 'sudo mysql -e "CREATE DATABASE phuria_test"'
  - 'sudo mysql phuria_test < tests/Phuria/SQLBuilder/Test/Resources/schema.sql'
script:
  - 'phpunit tests'